env:
  global:
      - REPO_DIR="LIBTwinSVM"
      # Also see DAILY_COMMIT below
      - BUILD_COMMIT=v0.2.0
      - PLAT=x86_64
      - UNICODE_WIDTH=32
      - BUILD_DEPENDS="cython numpy matplotlib pyQt5 sklearn pandas xlsxwriter joblib numpydoc==0.7.0"
      - TEST_DEPENDS="numpy matplotlib pyQt5 sklearn pandas xlsxwriter joblib pytest"

language: python
# Default Python version is usually 2.7
python: 3.5
sudo: required
dist: trusty
services: docker

matrix:
  exclude:
      # Exclude the default Python 3.5 build
      - python: 3.5
  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5

    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6

    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7

branches: wheel

before_install:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT

#deploy:
#    provider: releases
#    api_key: "37e2caa7380bbe38a4d1619d2c92faa9f92a019f"
#    file_glob: true
#    file: ${TRAVIS_BUILD_DIR}/wheelhouse/*
#    skip_cleanup: true
#    draft: true
#    on:
#      branches: wheel     
after_success:
    
    #- cd "${TRAVIS_BUILD_DIR}/wheelhouse/"
    #- curl --verbose --progress-bar --ipv4 --connect-timeout 8 --max-time 120 --retry 128 --ftp-pasv -T "{$(echo *.whl | tr ' ' ',')}" -u "${FTP_USER}:${FTP_PWD}" ftp://ftp.mirblog.ir/   
    - pip install dropbox
    - python upload.py ${TRAVIS_BUILD_DIR}/wheelhouse/
#
#    # Upload wheels to Rackspace container
#    - pip install wheelhouse-uploader
#    - python -m wheelhouse_uploader upload --local-folder
#          ${TRAVIS_BUILD_DIR}/wheelhouse/
#          $UPLOAD_ARGS
#          $CONTAINER